WATCH=all
WATCHFMT="%D %T %S%n%s %l %a %M"
HISTSIZE=256
case $HOST in
	(datura.dylex.net)
		MAIL=$HOME/mail/spool
		MAILPATH=$MAIL'?>> New mail':$HOME/mail/fm'?>> Mmm... freshmeat':$HOME/mail/netflix'?>> Netflix activity':$HOME/.pork/dylexs/logs'?>> New pork messages in $_'
		MAILCHECK=60
		;;
esac

setopt ignoreeof
mesg y
uname -a
w
