WATCH=all
WATCHFMT="%D %T %S%n%s %l %a %M"
case $HOST in
	(datura.dylex.net)
		MAIL=$HOME/mail/spool
		MAILPATH=$MAIL'?>> New mail':$HOME/mail/fm'?>> Mmm... freshmeat':$HOME/mail/netflix'?>> Netflix activity':$HOME/.purple/logs'?>> New purple messages in $_'
		MAILCHECK=60
		;;
esac

setopt ignoreeof
mesg y
uname -a
w

[[ ! -f ${ZDOTDIR:-~}/.zlogin.local ]] || . ${ZDOTDIR:-~}/.zlogin.local
